#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EnRouteApi.Android.Tests.Resource", IsApplication=true)]

namespace EnRouteApi.Android.Tests
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::EnRouteApi.Android.Tests.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::EnRouteApi.Android.Tests.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::EnRouteApi.Android.Tests.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::EnRouteApi.Android.Tests.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::EnRouteApi.Android.Tests.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::EnRouteApi.Android.Tests.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::EnRouteApi.Android.Tests.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::EnRouteApi.Android.Tests.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::EnRouteApi.Android.Tests.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::EnRouteApi.Android.Tests.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::EnRouteApi.Android.Tests.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::EnRouteApi.Android.Tests.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::EnRouteApi.Android.Tests.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::EnRouteApi.Android.Tests.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::EnRouteApi.Android.Tests.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::EnRouteApi.Android.Tests.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::EnRouteApi.Android.Tests.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::EnRouteApi.Android.Tests.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::EnRouteApi.Android.Tests.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::EnRouteApi.Android.Tests.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::EnRouteApi.Android.Tests.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::EnRouteApi.Android.Tests.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_wru = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int glogo_v2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_00 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_01 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_02 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_03 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_04 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_05 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_06 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notification_07 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notification_08 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_09 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int notification_arrived = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int notification_low_battery = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int notification_received = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int notification_warning = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int OptionHostName = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int OptionPort = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int OptionRemoteServer = 2131230720;
			
			// aapt resource value: 0x7f080010
			public const int OptionsButton = 2131230736;
			
			// aapt resource value: 0x7f08000b
			public const int ResultFullName = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public const int ResultMessage = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int ResultResultState = 2131230732;
			
			// aapt resource value: 0x7f08000a
			public const int ResultRunSingleMethodTest = 2131230730;
			
			// aapt resource value: 0x7f08000e
			public const int ResultStackTrace = 2131230734;
			
			// aapt resource value: 0x7f080006
			public const int ResultsFailed = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int ResultsId = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int ResultsIgnored = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int ResultsInconclusive = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int ResultsMessage = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int ResultsPassed = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int ResultsResult = 2131230724;
			
			// aapt resource value: 0x7f08000f
			public const int RunTestsButton = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int TestSuiteListView = 2131230737;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int options = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int results = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int test_result = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int test_suite = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f060000
			public const int common_days_1d = 2131099648;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int arrived_at_destination = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int click_to_expire = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int click_to_reply = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int click_to_view = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int fcm_fallback_notification_channel_label = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int glympse_gdpr_accept = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int glympse_gdpr_message = 2131034129;
			
			// aapt resource value: 0x7f050005
			public const int glympse_was_received = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int group_invitation_was_received = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int low_battey_warning = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int no_active_glympses = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int no_network_connection = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int rate_limited = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int remaining_details = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int remaining_title = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int remaining_title_glympse = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int reply_with_a_glympse = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int request_was_received = 2131034127;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int NotificationText = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int NotificationTitle = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
