#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EnRouteApi.Android.Tests.Resource", IsApplication=true)]

namespace EnRouteApi.Android.Tests
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Nunit.Runner.Resource.String.ApplicationName = global::EnRouteApi.Android.Tests.Resource.String.ApplicationName;
			global::Nunit.Runner.Resource.String.Hello = global::EnRouteApi.Android.Tests.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::EnRouteApi.Android.Tests.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::EnRouteApi.Android.Tests.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::EnRouteApi.Android.Tests.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::EnRouteApi.Android.Tests.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int bg_wru = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int glogo_v2 = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int notification_00 = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int notification_01 = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int notification_02 = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int notification_03 = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int notification_04 = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int notification_05 = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int notification_06 = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int notification_07 = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int notification_08 = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int notification_09 = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int notification_arrived = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int notification_low_battery = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int notification_received = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int notification_warning = 2130771983;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7F030000
			public const int common_days_1d = 2130903040;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040002
			public const int arrived_at_destination = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int click_to_expire = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int click_to_reply = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int click_to_view = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int glympse_gdpr_accept = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int glympse_gdpr_message = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int glympse_was_received = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int group_invitation_was_received = 2130968585;
			
			// aapt resource value: 0x7F040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7F04000A
			public const int low_battey_warning = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int no_active_glympses = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int no_network_connection = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int rate_limited = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int remaining_details = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int remaining_title = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int remaining_title_glympse = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int reply_with_a_glympse = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int request_was_received = 2130968594;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F050000
			public const int NotificationText = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int NotificationTitle = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
